export const bankingContacts = [
  {
    bank: "Alior Bank",
    people: [
      { name: "Łukasz Rogala", phone: "782 891 451", role: "Partner" },
      { name: "Paweł Stróżyk", phone: "882 824 541", role: "Wsparcie" },
      { name: "Tomasz Krawczyk", phone: "606 650 914", role: "Wsparcie" },
      { name: "Anna Orlińska", phone: "531 401 921", role: "Wsparcie" },
    ],
  },
  {
    bank: "BNP Paribas",
    people: [
      { name: "Beata Krzemińska", phone: "664 047 642", role: "Partner" },
    ],
  },
  {
    bank: "Inbank",
    people: [
      { name: "Paweł Stróżyk", phone: "882 824 541", role: "Opiekun" },
      { name: "Tomasz Krawczyk", phone: "606 650 914", role: "Opiekun" },
      { name: "Anna Orlińska", phone: "531 401 921", role: "Opiekun" },
    ],
  },
];

export const financialMaterials = [
  {
    title: "Porównanie ofert banków",
    points: [
      "Bank uzależnia przyznanie kredytu od zdolności kredytowej kredytobiorcy.",
      "Nie łączymy kredytów w ramach 1 produktu (w kilku bankach) — jeśli jest PV i ME, można podpisać PV w 1 banku, ME w 2.",
      "Wysokość kredytu musi być dokładnie taka sama, jak wartość produktu na umowie.",
      "Kredytobiorca musi być nabywcą na umowie.",
      "Do każdego kredytu wymagany jest podpisany przez kredytobiorcę/ów wniosek o kredyt ratalny — należy dołączyć go w CRM w pliki klienta.",
    ],
  },
  {
    title: "Alior Bank",
    points: [
      "Kredyt uruchamiany przed montażem, po dostawie elementów.",
      "Okres kredytowania: 12-114 mies. z karencją 6 miesięcy.",
      "Kredyt na oświadczenie: 38 400 PLN.",
      "Kwota kredytu: do 120 000 PLN.",
      "Koszt miesięczny: 0,50% / RRSO 10,56%.",
      "Możliwość łączenia dochodów: tak, ze współkredytobiorcą.",
      "Uruchomienie kredytu: po dostawie elementów do klienta.",
      "Płatność 1 raty zależy od wybranej linii kredytowej.",
      "Wiek klienta: od 18 do 80 lat.",
      "Promocja: karencja w spłacie 6 miesięcy od dnia sporządzenia kredytu.",
    ],
  },
  {
    title: "BNP Paribas",
    points: [
      "Kredyt uruchamiany i wypłacany po montażu.",
      "Okres kredytowania: 3-120 mies.",
      "Kredyt na oświadczenie: 38 000 PLN.",
      "Kwota kredytu: 300 PLN - 120 000 PLN.",
      "Koszt miesięczny: 0,55% / RRSO 11,14%.",
      "Możliwość łączenia dochodów: tak, ze współkredytobiorcą.",
      "Uruchomienie kredytu: po montażu.",
      "Płatność 1 raty: po 3 miesiącach od podpisania kredytu.",
      "Do 75 roku życia oferta bez ograniczeń, po 75 roku życia max 8 tys. i 24 miesiące.",
      "Promocja: karencja w spłacie 6 miesięcy po uruchomieniu kredytu.",
    ],
  },
  {
    title: "Inbank",
    points: [
      "Kredyt wypłacany po montażu.",
      "Kredyt na oświadczenie: 36 000 PLN.",
      "Kwota kredytu: 4 000 PLN - 100 000 PLN.",
      "Oprocentowanie nominalne: 11% / RRSO 11,72%.",
      "Możliwość łączenia dochodów: nie.",
      "Uruchomienie kredytu: po montażu.",
      "Płatność 1 raty: po 2 miesiącach od podpisania kredytu.",
      "Honorowane dochody z zagranicy po odpowiednim przeliczeniu.",
    ],
  },
];

export const incomeTypeOptions = [
  "Umowa o pracę",
  "Umowa o dzieło",
  "Umowa zlecenie",
  "Os. prowadząca działaność gospodarczą",
  "Spółka cywilna",
  "Emerytura",
  "Świadczenie przedemerytalne",
  "Renta",
  "Renta socjalna",
  "Renta resortowa",
  "Gospodarstwo rolne",
  "Działy specjalne produkcji rolnej",
  "Umowa najmu",
  "Mianowanie",
  "Powołanie",
  "Kontrakt marynarski",
  "Kontrakt wojskowy",
  "Kontrakt menedżerski",
  "Prezesi i członkowie zarządu",
  "Osoby duchowne",
  "Radny",
  "Posłowie",
];

export const pensionCardRequiredTypes = [
  "Emerytura",
  "Renta",
  "Renta socjalna",
  "Renta resortowa",
];

export const creditFormInitialData = {
  product_name: "",
  product_price: "",
  client_contribution: "",
  financed_amount: "",
  installments_count: "",
  payment_day: "",
  credit_number: "",
  borrower_pesel: "",
  coborrower_pesel: "",
  borrower_name: "",
  coborrower_name: "",
  borrower_id_number: "",
  coborrower_id_number: "",
  borrower_id_issue_date: "",
  coborrower_id_issue_date: "",
  borrower_id_expiry_date: "",
  coborrower_id_expiry_date: "",
  borrower_mother_maiden_name: "",
  coborrower_mother_maiden_name: "",
  borrower_marital_status: "",
  coborrower_marital_status: "",
  borrower_children_count: "",
  coborrower_children_count: "",
  borrower_children_birth_dates: "",
  coborrower_children_birth_dates: "",
  borrower_phone: "",
  coborrower_phone: "",
  borrower_email: "",
  coborrower_email: "",
  borrower_education: "",
  coborrower_education: "",
  borrower_home_street: "",
  borrower_home_postal: "",
  borrower_home_city: "",
  coborrower_home_street: "",
  coborrower_home_postal: "",
  coborrower_home_city: "",
  borrower_correspondence_street: "",
  borrower_correspondence_postal: "",
  borrower_correspondence_city: "",
  coborrower_correspondence_street: "",
  coborrower_correspondence_postal: "",
  coborrower_correspondence_city: "",
  borrower_installation_street: "",
  borrower_installation_postal: "",
  borrower_installation_city: "",
  coborrower_installation_street: "",
  coborrower_installation_postal: "",
  coborrower_installation_city: "",
  borrower_income_type: "",
  coborrower_income_type: "",
  borrower_pension_card_number: "",
  coborrower_pension_card_number: "",
  borrower_income_from: "",
  coborrower_income_from: "",
  borrower_income_to: "",
  coborrower_income_to: "",
  borrower_employer_nip: "",
  coborrower_employer_nip: "",
  borrower_employer_name: "",
  coborrower_employer_name: "",
  borrower_employer_phone: "",
  coborrower_employer_phone: "",
  borrower_position: "",
  coborrower_position: "",
  borrower_net_income: "",
  coborrower_net_income: "",
  borrower_monthly_expenses: "",
  coborrower_monthly_expenses: "",
  agency_name: "",
  representative_name: "",
  customer_signature: "",
  advisor_signature: "",
};